services:
  app:
    build: .
    container_name: job-junction-app
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./
          target: ./app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: jj
    ports:
      - 5432:5432
    volumes:
      - jj:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jj:
